FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build -- --output-path=dist --configuration=production

FROM node:18-alpine

RUN npm install -g http-server

WORKDIR /app

COPY --from=build /app/dist /app/dist

EXPOSE 4200

CMD ["http-server", "dist", "-p", "4200"]
